# Generated by Django 4.0.10 on 2024-04-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='professional_role',
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, help_text='Your Profession', max_length=255),
        ),
    ]
