# Generated by Django 4.0.10 on 2024-04-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_professional_role_user_profession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.FloatField(help_text='Duration in years'),
        ),
    ]
