# Generated by Django 4.0.10 on 2024-04-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_title_course_name_alter_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.FloatField(blank=True, help_text='Duration in years'),
        ),
    ]
