# Generated by Django 4.0.10 on 2024-07-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_equipment_specifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='categories',
            field=models.ManyToManyField(to='inventory.category'),
        ),
    ]
