# Generated by Django 4.2 on 2024-09-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_equipment_category_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='quantity_available',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
