# Generated by Django 4.0.10 on 2024-04-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('confirmation', 'Booking Confirmation'), ('cancellation', 'Booking Cancellation'), ('rejection', 'Booking Rejection'), ('reminder', 'Booking Reminders')], max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('status', models.BooleanField(choices=[('unread', 'Unread'), ('read', 'Read'), ('archived', 'Archived'), ('pending', 'Pending')], default=False)),
                ('sentAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
