# Generated by Django 4.2 on 2024-09-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentbooking',
            name='notes',
            field=models.TextField(blank=True, help_text='Add any addiional information here.', null=True),
        ),
        migrations.AddField(
            model_name='equipmentbooking',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipmentbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('in_use', 'In Use'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
